version: 2.1

orbs:
  python: circleci/python@2.5
  postgres: circleci/postgres@1.0

jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: circleci/postgres:9.6.2

    working_directory: ~/repo

    steps:
      - checkout
      - python/install-packages
      - postgres/postgres-setup:
          dbname: mydatabase
          username: myuser
          password: mypassword

      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python -m pytest

workflows:
  version: 2
  build:
    jobs:
      - build
