version: 2.1

#orbs
orbs:
  python: circleci/python@1.5.0
  heroku: circleci/heroku@1.2.6

jobs:
  build-test:
    docker:
      - image: cimg/python:3.12.0
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          key: arinze-cache
      - python/install-packages
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - save_cache:
          paths:
            - "python-apps"
          key: arinze-cache
            

workflows:
  my-workflow:
    jobs:
      - build-test